### ISSUE TITLE
20160525 서버 닫혔습니다

### ISSUE THREAD

**Issue by devbobos** [jaewoongh/telegram-bots#1]
사용량이 너무 많아서인지, 전기세가 연체된것인지 서버가 닫혔습니다
하루 빨리 김결정씨를 만나고 싶습니다 자장면 시켜야되서요 아 짬뽕도 먹고싶은데..

**Comment by jaewoongh** [comment]
으악 진짜 안 되네요!! 서버 자체는 살아 있는 것 같은데 김결정 앱에 문제가 생겼거나 한 모양입니다.
한번 확인해 보도록 할게요. 랩탑을 안 갖고 나와서 자정 즈음에야 가능할 것 같습니다ㅠ

**Comment by jaewoongh** [comment]
살려냈습니다. 오밤중에 고치는 바람에 김결정 뒷북 메시지가 늦은 시간 폰을 울리겠네요..
급작스럽게 뻗어 죄송하고 제보 주셔서 감사합니다!
