### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by finaleaf** [jaewoongh/telegram-bots#2]
안녕하세요.
텔레그램에서 김결정과 매우 잘 놀고있는 유저입니다.
다름이 아니라 김결정의 PHP 버전을 만들어 slack 봇으로 만들까 하는데 괜찮을런지요?
허가 해 주시면 착수하여 소스 공개할 예정입니다.
그럼 좋은 하루 되세요~

**Comment by jaewoongh** [comment]
어휴 물론 괜찮습니다 얼마든지 활용해 주세요.
이렇게 미리 언질까지 주시니 감사합니다.
혹시나 해서 MIT 라이센스 달아 두었습니다.
좋은 하루 되세요 😄
